language: php
php:
  - 5.4
  - 5.6
  - 7.0
  - 7.2
matrix:
  include:
    - php: 5.3
      dist: precise
sudo: false
before_script:
  - travis_retry composer self-update
  - travis_retry npm install -g grunt-cli
  - travis_retry npm install
  - if [ $(phpenv version-name) != "5.3" ]; then composer install; fi
  - if [ $(phpenv version-name) != "5.3" ]; then mysql -e 'create database xe_test;'; fi
  - if [ $(phpenv version-name) != "5.3" ]; then echo "USE mysql;\nUPDATE user SET password=PASSWORD('root')
    WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root; fi
  - if [ $(phpenv version-name) != "5.3" ]; then php -S localhost:8000 & fi
script:
  - grunt lint --force
  - grunt minify
  - if [ $(phpenv version-name) != "5.3" ]; then ./vendor/bin/codecept build; fi
  - if [ $(phpenv version-name) != "5.3" ]; then ./vendor/bin/codecept run -d --fail-fast --env travis; fi